#any time we'll make use of docker we've to be granted super user perms 
sudo: required

#making sure that travis knows we need docker cli pre-installed
services:
  - docker

#series of commands that we'll be executed before our tests are ran..
before_install:
  - docker build -t ahmeedaly/docker-react -f Dockerfile.dev .


script:
  # "-- -- coverage flag is added to automatically exit after performing tests and prevent hanging status"
  - docker run -e CI=true ahmeedaly/docker-react npm run test -- --coverage


#App code deplyment
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-reactApp"
  env: "Dockerreactapp-env"
  #All app files inside GitHub repo would be zipped up into one single file and will be
  #copied to a S3 Bucket on AWS
  bucket: "elasticbeanstalk-us-east-1-976852498315"
  bucket_path: "docker-reactApp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

